version: '3.8'

services:
  library-catalog:
      build: ./frontend
      image: library-catalog
      container_name: library-catalog
      environment:
        VIRTUAL_HOST: library-catalog.ru
        VIRTUAL_PORT: 80
      depends_on:
        - php-backend-library-catalog
      restart: unless-stopped
  php-backend-library-catalog:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-backend-library-catalog
    depends_on:
      - postgres
    networks:
      - network-library-catalog
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:1.29
    container_name: nginx-server-library-catalog
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-backend-library-catalog
    networks:
      - network-library-catalog

  postgres:
    image: postgres:18-alpine
    container_name: postgres-db-library-catalog
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-library-catalog:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network-library-catalog
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - network-library-catalog

volumes:
  postgres-data-library-catalog:

networks:
  network-library-catalog:
    driver: bridge
  proxy-network:
    external: true